### ISSUE TITLE
If your podcast is more than 10 episodes，Something happened

### ISSUE THREAD

**Issue by DavidFnck** [TheCraigHewitt/Seriously-Simple-Podcasting#135]
When my podcast is over 10 episodes, the feed only can show 10 episodes.

how to solve it?

I try to change the number, just like the image blow. But nothing change, maybe I didn’t do the right things.

![Seriously-Simple-Podcasting-bug](http://davidfnck.qiniudn.com/Seriously-Simple-Podcasting-bug.png)

**Comment by whyisjake** [comment]
There is a one hour cache set on that query. So, if you flush the cache, you should see 100 posts. Ideally, this is handy for setting up a new show to get all episodes into a client, like iTunes, once they have been added, I'd scale it back to 10 so that you don't have performance issues when fetching the feed.

**Comment by whyisjake** [comment]
Also, there is a filter called `ssp_feed_number_of_posts` where you can adjust the feed settings.

`add_filter( 'ssp_feed_number_of_posts', function($count) {return 100;} );`
