### ISSUE TITLE
Add RSS feed setting for description tag

### ISSUE THREAD

**Issue by jonathanbossenger** [TheCraigHewitt/Seriously-Simple-Podcasting#382]
- Off - use WordPress default excerpt functionality to generate the RSS episode description tag
- On - Use the full post_content, with html to generate the RSS episode description tag
- Move the 4000 char limit to Turbocharge only

**Comment by samkuhn** [comment]
Many thanks for investigating so quickly. Regarding our use case mentioned on wordpress.org support - we consume our feeds from native android / iOS apps and it's essential that we have complete post description html (since any cropping causes rendering issues in-app due to missing closing tags etc).

We were using content:encoded up until this issue surfaced which was performing perfectly.
content:encoded no longer seems to appear in any of our feeds however.

We are a little confused since the reason we switched to content:encoded a while back was because we found that all the other descriptions were being truncated at some character limit even before this latest update. 

Perhaps you help us understand how this latest proposal gets around that and if we'll still be able to rely on content:encoded (or other) to get guaranteed full post html moving forward.. Thanks.

**Comment by jonathanbossenger** [comment]
@samkuhn 

content:encoded should still appear in the feed, unless you have Turbocharge switched on, and then it will only show for the first 10 episodes. 

If you have Turbocharge switched off and content:encoded is not appearing in the feed at all then that is a separate bug that has crept in. If this is the case, could I ask you to log that by clicking on the New Issue button at the top of this page, and I'll investigate that at the same time.

Thanks

**Comment by samkuhn** [comment]
Thanks a lot Jonathan. Awesome support :)

We have checked and Turbocharge is defaulted to "Off" on all episodes and we still have no content:encoded tags in our feeds. We've opened a [new issue](https://github.com/TheCraigHewitt/Seriously-Simple-Podcasting/issues/383) as requested.

**Comment by jonathanbossenger** [comment]
@samkuhn I have completed development of this setting, as well as fixed the other bug you logged, are you comfortable downloading the zip from GitHub to test the updated version of the plugin?

https://github.com/TheCraigHewitt/Seriously-Simple-Podcasting/tree/feature/1.20.6-develop

**Comment by samkuhn** [comment]
Thanks guys we'll test asap.

**Comment by jonathanbossenger** [comment]
This has been fixed in version 1.20.6 of the plugin
