### ISSUE TITLE
Album post type with multiple audio files in a single album

### ISSUE THREAD

**Issue by tkittich** [TheCraigHewitt/Seriously-Simple-Podcasting#395]
Please add a feature to create albums!! 

This feature would make Seriously Simple Podcasting very useful for musicians, audiobook authors, teachers, religious preachers, and many others who organize audio files into an album or a topic. 

An album would have common meta data, e.g. same author, same album image, same episode type, same season number, same explicit or block. All these common data could be album properties and filled in only once. The episodes in the album would just have different audio files and other additional meta data. 

This feature would be super cool. 😄😄

**Comment by jonathanbossenger** [comment]
@tkittich the podcast playlist shortcode might work well for this requirement

https://support.castos.com/article/41-podcastplaylist-shortcode

I'm closing this ticket now, because our issues list is for bug tracking. If you would like to a submit a suggestion, please do so on our User Suggestions page https://feedback.castos.com/

Thanks
