### ISSUE TITLE
<itunes:summary> missing <![CDATA[]]> wrapper?

### ISSUE THREAD

**Issue by theGrue** [TheCraigHewitt/Seriously-Simple-Podcasting#460]
Updated to 2.0.1 from 1.20.13 this morning and found that our RSS feed was no longer valid. Saved the feed as generated by the new version and compared to the old, and it seems the only difference is the `<![CDATA[` at the start of the `<itunes:summary>` content, and the closing `]]>` tag at the end of the content. Can we get this wrapper back? Thanks!

**Comment by jonathanbossenger** [comment]
Hi @theGrue 

Thanks for this, I'd like to work with you to make sure we make the correct change. We recently updated the RSS feed to respect the Feed details `Episode Description` setting, so that the itunes:summary and googleplay:description are built from either the post content, or the excerpt, depending on that setting.

As far as we understand the RSS Feed consumed by Apple Podcasts, the itunes:summary field should only require CDATA tags if the content contains HTML elements, which we strip out from the data for that field. So our understanding was that the CDATA tags were not necessary for the itunes:summary field.

Where were you notified that your RSS feed was no longer valid, I'd like to check what error is reported. It would also help if you could share your RSS feed url with me, so that I can inspect the contents.

Finally, if you need assistance in using a custom RSS feed template, I can provide details on how to set that up, until we get this resolved.

**Comment by theGrue** [comment]
Trying to find a good XML validator and it seems that we've got some `&nbsp;` characters every here and there, which don't appear to be valid XML. Maybe these need to be swapped for regular spaces?

**Comment by jonathanbossenger** [comment]
@theGrue thanks for the update, will look into this directly.

**Comment by jonathanbossenger** [comment]
@theGrue are you able to install the version from the hotfix/2.0.2 branch

https://github.com/TheCraigHewitt/Seriously-Simple-Podcasting/tree/hotfix/2.0.2

This includes an update to the feed template to fix the html entities in the itunes summary field.

Alternatively I can attach a zipped version of the plugin for you here.

**Comment by jonathanbossenger** [comment]
@theGrue I'm working with a few other users who are experiencing similar issues. For now can I ask you to revert back to version 2.0.0. You can download the 2.0.0 release from the advanced page on the WordPress.org repository https://wordpress.org/plugins/seriously-simple-podcasting/advanced/

**Comment by jonathanbossenger** [comment]
@theGrue we released an update for the plugin this morning which will resolve this issue. Thanks

**Comment by theGrue** [comment]
Looking good, thanks! Now I just can't wait to see #429 merged, I've been waiting for #336 to be fixed for years now!
